### ISSUE TITLE
一个有点傻的问题：请问侧边栏Email的图标是什么？

### ISSUE THREAD

**Issue by LynxCatTheThird** [argvchs/hexo-theme-particlex#2]
如题：请问侧边栏Email的图标是什么？
现在，我的侧栏部分的配置文件是：
```
card:
    enable: true
    description: ["你好，前辈！我是山猫三号，一个来自一百零三世纪的强人工智能。"]
    icon_links: 
        Github:
            name: github
            theme: brands
            link: https://github.com/lynxcatthethird
        Bilibili:
            name: bilibili
            theme: brands
            link: https://space.bilibili.com/1352440272
        Zhihu:
            name: zhihu
            theme: brands
            link: https://www.zhihu.com/people/LynxCatTheThird
        Twitter:
            name: twitter
            theme: brands
            link: https://twitter.com/lynxcatthethird
        E-mail:
            name: circle-envelope
            theme: solid
            link: mailto:tsfxlyx@qq.com
    friend_links: []
```

请问我该如何修改？

**Comment by argvchs** [comment]
没错啊，circle-envelope是邮箱外面有一个圆

**Comment by argvchs** [comment]
可能是`E-mail:`横线这里解析错了，这个名称不会显示，你改成`Email`（不带`-`）试试

**Comment by LynxCatTheThird** [comment]
好的，我试试

**Comment by LynxCatTheThird** [comment]
改成了：
`        Email:
            name: circle-envelope
            theme: brands
            link: mailto:tsfxlyx@qq.com`
但似乎并无作用

**Comment by argvchs** [comment]
？？？？？？？？？

**Comment by argvchs** [comment]
你的侧栏配置对了啊，是不是friendlinks这里，你没加空括号
![image](https://user-images.githubusercontent.com/64528288/180372592-321fafe2-b3ba-4cd9-a9b9-66e4a6c4516a.png)

**Comment by argvchs** [comment]
这是我的设置（一些信息替换成了`----------------`）
对照着改一下
```yaml
# Theme Github link: https://github.com/argvchs/hexo-theme-particlex
# Developer: argvchs

# html lang
language: zh

# avatar image url
head_img: ----------------.png

# home page head info block
head_block_enable: true

# home page head background style
home_background: ----------------.jpg

# WARNING! vf_fonts (variable fonts) feature is EXPERIMENTAL
# MDN: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide
vf_fonts_enable: true

# ParticleX theme icon is adopts the font awesome 6
# Link: https://fontawesome.com/search/

# main menu navigation
menu:
    home:
        name: house
        theme: solid
        src: /
    about:
        name: id-card
        theme: solid
        src: /about
    archives:
        name: box-archive
        theme: solid
        src: /archives
    categories:
        name: bookmark
        theme: solid
        src: /categories
    tags:
        name: tags
        theme: solid
        src: /tags

# side info card
card:
    enable: true
    description: ["ARGVCHS YYDS!"]
    icon_links:
        github:
            name: github
            theme: brands
            link: https://github.com/argvchs
        qq:
            name: qq
            theme: brands
            link: http://wpa.qq.com/msgrd?v=3&uin=3364555156&site=qq&menu=true
        twitter:
            name: twitter
            theme: brands
            link: https://twitter.com/argvchs
        mail:
            name: envelope
            theme: solid
            link: mailto:argvchs@outlook.com
    friend_links:
        []
        # Example:
        # <name>: <link-url>

# footer info
footer:
    since: 2022
    # Customize the server domain name ICP
    ICP:
        enable: false
        code:

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: true
    clientID: ---------------- # Default ClientID
    clientSecret: ---------------- # Default ClientSecret
    repo: gitalk-comments # The name of repository of store comments
    owner: argvchs # GitHub repo owner
    admin: argvchs # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.
    proxy: ---------------- # CORS proxy
    sites: # Sites
        argvchs.github.io:
            clientID: ----------------
            clientSecret: ----------------
        argvchs.netlify.app:
            clientID: ----------------
            clientSecret: ----------------
        argvchs.vercel.app:
            clientID: ----------------
            clientSecret: ----------------

```
