### ISSUE TITLE
主题如何自定义页脚icp链接?

### ISSUE THREAD

**Issue by hatsuyuki2333** [argvchs/hexo-theme-particlex#24]

**Comment by argvchs** [comment]
看 [README](https://github.com/argvchs/hexo-theme-particlex/blob/master/README.md) 啊
在 config.yml 里的 `footer/ICP` 配置
```yaml
footer:
    since: 20xx
    ICP:
        enable: true
        code: # ICP code
```
