### ISSUE TITLE
配合插件的bug

### ISSUE THREAD

**Issue by wangleih** [argvchs/hexo-theme-particlex#36]
使用hexo-bilibili-bangumi，hexo-steam-games这两个插件生成的页面无法翻页。原插件生成页面中按键，现在点不了，其他hexo主题可以，但particleX不行。

**Comment by argvchs** [comment]
~~我不道啊~~

添加导航栏链接试试

```yaml
# _config.yml
menu:
    home:
        name: house
        theme: solid
        src: /
    about:
        name: id-card
        theme: solid
        src: /about
    archives:
        name: box-archive
        theme: solid
        src: /archives
    categories:
        name: bookmark
        theme: solid
        src: /categories
    tags:
        name: tags
        theme: solid
        src: /tags
```

显示很乱的话调一下 CSS
