### ISSUE TITLE
标签和分组页无法显示标签

### ISSUE THREAD

**Issue by xiangrongonline** [argvchs/hexo-theme-particlex#43]
大佬，能帮忙看一下这是咋回事吗，为啥我在文章的markdown上写上标签和分组类型后在文章上有标签和分组标志，但是标签和分组页面什么也没有是需要在这两个页面的index.md文件上还得加上些什么吗？
![image](https://user-images.githubusercontent.com/102706409/208624604-c7ccb393-3d8e-42aa-9284-c40a39ce7864.png)
![image](https://user-images.githubusercontent.com/102706409/208624604-c7ccb393-3d8e-42aa-9284-c40a39ce7864.png)

**Comment by xiangrongonline** [comment]
![image](https://user-images.githubusercontent.com/102706409/208625303-40e3e2c5-be1d-453c-8a91-26f9d237768f.png)

**Comment by LynxCatTheThird** [comment]
我也遇到过这个问题，试了一圈，也不知道哪个操作解决的，但可能是在在 _blog/sources/tags_ 里新建 _index.md_ 解决的

**Comment by xiangrongonline** [comment]
我建了，但是这两个页面什么也没有
![image](https://user-images.githubusercontent.com/102706409/208817765-87e83262-5add-43e8-9dfc-d552612c3d85.png)
![image](https://user-images.githubusercontent.com/102706409/208817848-004578dd-b52e-418a-a628-cf0ca6d7543c.png)
是还得在index.md里面写东西吗

**Comment by Yuzi0201** [comment]
https://argvchs.github.io/2022/04/17/hexo-blog-2/
↑这是repo主的教程，是不是漏了什么。
另外，你给我发的邮件，我回复就显示发件地址不存在，你的outlook邮箱是不是配置有点问题？？

**Comment by xiangrongonline** [comment]
是按照作者博客这样做的
但是不清楚为什么标签页面没有显示存在的标签，但是他的子页面是正常工作的，好奇怪
我的outlook邮箱我不清楚怎么了，我都不知道，是找不到吗，那用邮箱号能够找到吗

**Comment by Yuzi0201** [comment]
> 是按照作者博客这样做的
> 但是不清楚为什么标签页面没有显示存在的标签，但是他的子页面是正常工作的，好奇怪
> 我的outlook邮箱我不清楚怎么了，我都不知道，是找不到吗，那用邮箱号能够找到吗

把hexo的config和主题的config贴出来看看呢「隐去一下敏感信息」

**Comment by xiangrongonline** [comment]
### 根目录下
```yml
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
```
### 主题目录下
```yml
menu:
  主页:
    name: house
    theme: solid
    src: /
  关于我:
    name: id-card
    theme: solid
    src: /about
  存档:
    name: box-archive
    theme: solid
    src: /archives
  分类:
    name: bookmark
    theme: solid
    src: /categories
  标签:
    name: tags
    theme: solid
    src: /tags
```
应该就这么基础用到了标签和分类
