### ISSUE TITLE
小改的过程中发生了一点问题

### ISSUE THREAD

**Issue by uncoveredfigure** [argvchs/hexo-theme-particlex#54]
在主页面下拉后背景白花花的感觉有点单调，于是在partclex.css文件中修改了body的背景颜色，但是显示效果中footer部分出现异常
<img width="1272" alt="捕获" src="https://user-images.githubusercontent.com/91234861/214224553-83e1f676-6b78-48e6-9bc1-f854642f5ae7.PNG">
但是本人能力有限，在footer的css部分找不到问题来源

**Comment by argvchs** [comment]
> 昨天忙着打 Florr.io 没注意有一个 Issue。。。

这个 Footer 的颜色是你自己调的吧。。

**Comment by argvchs** [comment]
https://github.com/argvchs/hexo-theme-particlex/blob/1eb9bf9f233e004a815c59e80ecec76a9bf602b3/source/css/particlex.css#L720-L726

在 `body` 的 `background: #f6f8fa;` 这里修改啊

**Comment by uncoveredfigure** [comment]
我这个背景只是在这里加了一条渐变色属性：
background-image: linear-gradient( 174.2deg,  rgba(255,244,228,1) 7.1%, rgba(240,246,238,1) 67.4% );
然后发生这奇怪的现象

**Comment by argvchs** [comment]
可以先这样

放一个背景元素在 `body` 里面
```ejs
<div id="background"></div>
```

然后设置样式

```css
#background {
    width: 100vw;
    height: 100vh;
    position: fixed;
    background: linear-gradient(174.2deg, rgba(255, 244, 228, 1) 7.1%, rgba(240, 246, 238, 1) 67.4%);
    z-index: -1;
}
```
