### ISSUE TITLE
顶部导航跳转异常

### ISSUE THREAD

**Issue by fightinggg** [argvchs/hexo-theme-particlex#6]
直接看例子
https://fightinggg.github.io/Hexo-Boot-Demo-Pages/particlex/RFTXWO.html

顶部导航应该跳转到https://fightinggg.github.io/Hexo-Boot-Demo-Pages/particlex/
但是他跳转到了https://fightinggg.github.io/

配置文件
https://github.com/fightinggg/Hexo-Boot-Demo-Pages/blob/master/particlex/debug/_multiconfig.yml#L65

**Comment by argvchs** [comment]
竟然用的是多主题？啊这
您的hexo-boot有主题的`_config.yml`吗？（不是`_multiconfig`，那是站点配置）
如果有，改一下`menu`配置
```yaml
menu:
    home:
        name: house
        theme: solid
        src: /Hexo-Boot-Demo-Pages/particlex
    about:
        name: id-card
        theme: solid
        src: /Hexo-Boot-Demo-Pages/particlex/about
    archives:
        name: box-archive
        theme: solid
        src: /Hexo-Boot-Demo-Pages/particlex/archives
    categories:
        name: bookmark
        theme: solid
        src: /Hexo-Boot-Demo-Pages/particlex/categories
    tags:
        name: tags
        theme: solid
        src: /Hexo-Boot-Demo-Pages/particlex/tags

```
