### ISSUE TITLE
代码展示异常

### ISSUE THREAD

**Issue by fightinggg** [argvchs/hexo-theme-particlex#7]
例子：https://fightinggg.github.io/Hexo-Boot-Demo-Pages/particlex/RFTXWO.html

现有状态：
![image](https://user-images.githubusercontent.com/42932982/182014915-c933cd27-d512-4c4e-9e4c-02993b2de88d.png)

**Comment by argvchs** [comment]
`_config.yml`（不是主题文件夹的）里`highlight`和`prismjs`设置改一下

```yaml
highlight:
    enable: false
    line_number: true
    auto_detect: false
    tab_replace: ""
    wrap: true
    hljs: false
prismjs:
    enable: false
    preprocess: true
    line_number: true
    tab_replace: ""
```
