### ISSUE TITLE
我有疑问~

### ISSUE THREAD

**Issue by yoshino2333** [argvchs/hexo-theme-particlex#71]
如何添加固定背景，效果如图
![QQ截图20230416165911](https://user-images.githubusercontent.com/105909793/232288232-f6e34ffb-4651-433d-9818-431f71bcb78f.png)
滚动背景不会动的那种效果
我是个什么都不懂的小白

**Comment by argvchs** [comment]
配置里似乎是不能添加固定背景的（
所以要自定义，可以在 `main.css` 里这样写

```css
body {
    background-image: url(....);
}
```
